### ISSUE TITLE
how do yourecompile robojs everytime toolbox updates node or electron?

### ISSUE THREAD

**Issue by KKonaW** [Midoriykawa/BERN#1]
btw thisis the undrm im using

//////////////////////
const fs = require('fs');

const DRMKEY = ;
const file = "./index.js"
const output = "./index-out.js"
const regex = /\((\d+?)\^\(DRMKEY<?<?(\d+)?\)\)/g

let data = fs.readFileSync(file, "utf8");
let match;

let result = data.replace(regex, (text, base, shift) => {
    shift = shift ? parseInt(shift) : 0;
    base = parseInt(base);
    return base ^ (DRMKEY << shift);
});

fs.writeFileSync(output, result);

//////////////////////

**Comment by Midoriykawa** [comment]
nmp robojs install

**Comment by Midoriykawa** [comment]
add me discord Kishirika Kishirisu#6329

**Comment by KKonaW** [comment]
> 
> 
> add me discord Kishirika Kishirisu#6329

rakko#1155
![Untitled](https://user-images.githubusercontent.com/35492207/87979312-ba679380-ca86-11ea-9683-0bdb442b6581.png)

**Comment by Midoriykawa** [comment]
Open
